services:
    mariadb:
        container_name: movie-app_mariadb
        ports:
            - 3306:3306
        image: mariadb:10.8
        restart: always
        volumes: 
            - mariadb-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${dbPassword}

    php:
        container_name: movie-app_php
        build: ./
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html/
        env_file:
            - ./app/config/.env
        links:
            - mariadb

    phpmyadmin:
        container_name: movie-app_phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8000:80
        environment:
            - PMA_HOST=mariadb
        depends_on:
            - mariadb

volumes:
     mariadb-data:
