services:
    mariadb:
        container_name: movie-app_mariadb
        ports:
            - 3306:3306
        image: mariadb:10.8
        volumes: 
            - ./app/config/database.sql:/var/lib/mysql
        env_file:
            - ./app/config/.env
        environment:
            - MYSQL_DATABASE=${dbName}
            - MYSQL_HOST=${dbServerName}
            - MYSQL_USER=${dbUsername}
            - MYSQL_PASSWORD=${dbPassword}

    php:
        container_name: movie-app_php
        build: ./
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html/
        env_file:
            - ./app/config/.env
        links:
            - mariadb
